/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Nov 09 16:49:34 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.estarcom.cnis.cssn.salesystem.order.service;

import java.io.Serializable;
import java.util.Date;

/**
 *   ���ְ�Ȩ��¼ lixiankai 2013-11-07
 * @author Administrator
 *
 */
public abstract class AbstractTProductStandardElec
    implements Serializable
{
    
    private int hashValue = 0;
    private java.lang.Long id;
    private java.lang.Long a001;
    private java.lang.String batch_no;
    private java.lang.String fileName;
    private java.lang.Long fileSize;
    private java.lang.String pageFormat;
    private java.lang.Long pageNnumber;
    private java.lang.String funcType;
    private java.lang.String transType;
    private java.lang.String language;
    private java.lang.String elecEntity_type;
    private java.lang.String remark;
    private java.lang.String auditingstatus;
    private java.lang.String quarry;
    private java.lang.String pdf_from;
    private java.lang.Long inlib_elecEntity_id;
    private java.lang.String whole_text;
    private java.lang.Long basic_price;
    private Float price;
    private java.lang.String upload_unit;
    private Date upload_date;
    private java.lang.String checked_person;
    private Date checked_date;
    private java.lang.String service_unit;
    private java.lang.String filePath;

	

	public AbstractTProductStandardElec(Long id) {
		super();
		this.id = id;
	}


	public AbstractTProductStandardElec() {
		super();
	}


	public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof DrmRecord))
            return false;
        DrmRecord that = (DrmRecord) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int itemIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + itemIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }


	public java.lang.Long getId() {
		return id;
	}


	public void setId(java.lang.Long id) {
		this.id = id;
	}


	


	public int getHashValue() {
		return hashValue;
	}


	public void setHashValue(int hashValue) {
		this.hashValue = hashValue;
	}


	public java.lang.Long getA001() {
		return a001;
	}


	public void setA001(java.lang.Long a001) {
		this.a001 = a001;
	}


	public java.lang.String getBatch_no() {
		return batch_no;
	}


	public void setBatch_no(java.lang.String batch_no) {
		this.batch_no = batch_no;
	}


	public java.lang.String getFileName() {
		return fileName;
	}


	public void setFileName(java.lang.String fileName) {
		this.fileName = fileName;
	}


	public java.lang.Long getFileSize() {
		return fileSize;
	}


	public void setFileSize(java.lang.Long fileSize) {
		this.fileSize = fileSize;
	}


	public java.lang.String getPageFormat() {
		return pageFormat;
	}


	public void setPageFormat(java.lang.String pageFormat) {
		this.pageFormat = pageFormat;
	}


	public java.lang.Long getPageNnumber() {
		return pageNnumber;
	}


	public void setPageNnumber(java.lang.Long pageNnumber) {
		this.pageNnumber = pageNnumber;
	}


	public java.lang.String getFuncType() {
		return funcType;
	}


	public void setFuncType(java.lang.String funcType) {
		this.funcType = funcType;
	}


	public java.lang.String getTransType() {
		return transType;
	}


	public void setTransType(java.lang.String transType) {
		this.transType = transType;
	}


	public java.lang.String getLanguage() {
		return language;
	}


	public void setLanguage(java.lang.String language) {
		this.language = language;
	}


	public java.lang.String getElecEntity_type() {
		return elecEntity_type;
	}


	public void setElecEntity_type(java.lang.String elecEntity_type) {
		this.elecEntity_type = elecEntity_type;
	}


	public java.lang.String getAuditingstatus() {
		return auditingstatus;
	}


	public void setAuditingstatus(java.lang.String auditingstatus) {
		this.auditingstatus = auditingstatus;
	}


	public java.lang.String getQuarry() {
		return quarry;
	}


	public void setQuarry(java.lang.String quarry) {
		this.quarry = quarry;
	}


	public java.lang.String getPdf_from() {
		return pdf_from;
	}


	public void setPdf_from(java.lang.String pdf_from) {
		this.pdf_from = pdf_from;
	}


	public java.lang.Long getInlib_elecEntity_id() {
		return inlib_elecEntity_id;
	}


	public void setInlib_elecEntity_id(java.lang.Long inlib_elecEntity_id) {
		this.inlib_elecEntity_id = inlib_elecEntity_id;
	}


	public java.lang.String getWhole_text() {
		return whole_text;
	}


	public void setWhole_text(java.lang.String whole_text) {
		this.whole_text = whole_text;
	}


	public java.lang.Long getBasic_price() {
		return basic_price;
	}


	public void setBasic_price(java.lang.Long basic_price) {
		this.basic_price = basic_price;
	}


	public Float getPrice() {
		return price;
	}


	public void setPrice(Float price) {
		this.price = price;
	}


	public java.lang.String getUpload_unit() {
		return upload_unit;
	}


	public void setUpload_unit(java.lang.String upload_unit) {
		this.upload_unit = upload_unit;
	}


	public Date getUpload_date() {
		return upload_date;
	}


	public void setUpload_date(Date upload_date) {
		this.upload_date = upload_date;
	}


	public java.lang.String getChecked_person() {
		return checked_person;
	}


	public void setChecked_person(java.lang.String checked_person) {
		this.checked_person = checked_person;
	}

	public Date getChecked_date() {
	
		return checked_date;
	}


	
	public void setChecked_date(Date checkedDate) {
	
		checked_date = checkedDate;
	}


	public java.lang.String getService_unit() {
		return service_unit;
	}


	public void setService_unit(java.lang.String service_unit) {
		this.service_unit = service_unit;
	}


	public java.lang.String getFilePath() {
		return filePath;
	}


	public void setFilePath(java.lang.String filePath) {
		this.filePath = filePath;
	}


	public java.lang.String getRemark() {
		return remark;
	}


	public void setRemark(java.lang.String remark) {
		this.remark = remark;
	}


	

}
