package cn.gov.cnis.cssn.wssort;

/**
 * Basewslog generated by MyEclipse Persistence Tools
 */

public class Basewslog implements java.io.Serializable {

	// Fields

	private Integer id;

	private String loginname;

	private String wsname;

	private String errorinfo;

	private String calltime;

	private String wsip;

	private String remark;

	private String inputfield;

	private String outputfield;

	// Constructors

	public String getInputfield() {
		return inputfield;
	}

	public void setInputfield(String inputfield) {
		this.inputfield = inputfield;
	}

	public String getOutputfield() {
		return outputfield;
	}

	public void setOutputfield(String outputfield) {
		this.outputfield = outputfield;
	}

	/** default constructor */
	public Basewslog() {
	}

	/** full constructor */
	public Basewslog(String loginname, String wsname, String errorinfo,
			String calltime, String wsip, String remark) {
		this.loginname = loginname;
		this.wsname = wsname;
		this.errorinfo = errorinfo;
		this.calltime = calltime;
		this.wsip = wsip;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getWsname() {
		return this.wsname;
	}

	public void setWsname(String wsname) {
		this.wsname = wsname;
	}

	public String getErrorinfo() {
		return this.errorinfo;
	}

	public void setErrorinfo(String errorinfo) {
		this.errorinfo = errorinfo;
	}

	public String getCalltime() {
		return this.calltime;
	}

	public void setCalltime(String calltime) {
		this.calltime = calltime;
	}

	public String getWsip() {
		return this.wsip;
	}

	public void setWsip(String wsip) {
		this.wsip = wsip;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}